/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Get Rule Debug Log by Execution ID API endpoint
 *   version: 1
 */

import { z } from '@kbn/zod';

export type GetRuleDebugLogByExecutionIdRequestQuery = z.infer<
  typeof GetRuleDebugLogByExecutionIdRequestQuery
>;
export const GetRuleDebugLogByExecutionIdRequestQuery = z.object({
  /**
   * Page number to return
   */
  page: z.coerce.number().int().optional().default(1),
  /**
   * Number of results per page
   */
  per_page: z.coerce.number().int().optional().default(20),
});
export type GetRuleDebugLogByExecutionIdRequestQueryInput = z.input<
  typeof GetRuleDebugLogByExecutionIdRequestQuery
>;

export type GetRuleDebugLogByExecutionIdRequestParams = z.infer<
  typeof GetRuleDebugLogByExecutionIdRequestParams
>;
export const GetRuleDebugLogByExecutionIdRequestParams = z.object({
  /**
   * Saved object ID of the rule to get debug log for
   */
  ruleId: z.string().min(1),
  /**
   * Execution ID of the rule to get debug log for
   */
  executionId: z.string().min(1),
});
export type GetRuleDebugLogByExecutionIdRequestParamsInput = z.input<
  typeof GetRuleDebugLogByExecutionIdRequestParams
>;

export type GetRuleDebugLogByExecutionIdResponse = z.infer<
  typeof GetRuleDebugLogByExecutionIdResponse
>;
export const GetRuleDebugLogByExecutionIdResponse = z.object({}).catchall(
  z.array(
    z.object({
      message: z.string().optional(),
    })
  )
);
