/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

/*
 * NOTICE: Do not edit this file manually.
 * This file is automatically generated by the OpenAPI Generator, @kbn/openapi-generator.
 *
 * info:
 *   title: Get Rule Debug Log API endpoint
 *   version: 1
 */

import { z } from '@kbn/zod';

export type GetRuleExecutionsWithDebugLogRequestParams = z.infer<
  typeof GetRuleExecutionsWithDebugLogRequestParams
>;
export const GetRuleExecutionsWithDebugLogRequestParams = z.object({
  /**
   * Saved object ID of the rule to get debug log for
   */
  ruleId: z.string().min(1),
});
export type GetRuleExecutionsWithDebugLogRequestParamsInput = z.input<
  typeof GetRuleExecutionsWithDebugLogRequestParams
>;

export type GetRuleExecutionsWithDebugLogResponse = z.infer<
  typeof GetRuleExecutionsWithDebugLogResponse
>;
export const GetRuleExecutionsWithDebugLogResponse = z.array(z.string());
